from ultralytics import YOLO
import os

current_directory = os.path.dirname(os.path.abspath(__file__))
best_pt_path = os.path.join(current_directory, 'best.pt')

model = YOLO(best_pt_path)
new_names_dict = {
    0: "DP.135 - Het tat ca moi lenh cam",
    1: "P.102 - Bien bao cam di nguoc chieu",
    2: "P.103a - Bien bao cam xe oto",
    3: "P.103b - Bien bao cam xe oto re phai",
    4: "P.103c - Bien bao cam xe oto re trai",
    5: "P.104 - Bien bao cam xe may",
    6: "P.106a - Bien bao cam xe oto tai",
    7: "P.106b - Bien bao cam xe oto tai tren 2,5 tan",
    8: "P.107a - Bien bao cam xe oto khach",
    9: "P.112 - Bien bao cam nguoi di bo",
    10: "P.115 - Han che tai trong toan xe",
    11: "P.117 - Bien bao han che chieu cao",
    12: "P.123a - Bien bao cam re trai",
    13: "P.123b - Bien bao cam re phai",
    14: "P.124a - Bien bao cam quay dau",
    15: "P.124b - Bien bao cam oto quay dau",
    16: "P.124c - Bien bao camre trai quay dau",
    17: "P.125 - Bien bao cam vuot",
    18: "P.127 - Bien bao gioi han toc do",
    19: "P.128 - Bien bao cam coi xe",
    20: "P.130 - Bien bao cam dung do xe",
    21: "P.131a - Bien bao cam do xe",
    22: "P.137 - Bien bao cam re trai va phai",
    23: "P.245a - Bien bao di cham",
    24: "R.301c - Bien bao chi dan re trai",
    25: "R.301d - Bien bao chi dan re phai",
    26: "R.301e - Bien bao chi duoc re trai",
    27: "R.302a - Bien bao chi dan di vong sang phai",
    28: "R.302b - Bien bao chi dan di vong sang trai",
    29: "R.303 - Bien bao giao nhau voi vong xuyen",
    30: "R.407a - Bien bao duong mot chieu",
    31: "R.409 - Bien bao cho quay dau xe",
    32: "R.425 - Bien bao hieu benh vien",
    33: "R.434 - Bien bao ben xe buyt",
    34: "S.509a - Chieu cao an toan 5m",
    35: "W.201a - Bien bao cho ngoat nguy hiem ben trai",
    36: "W.201b -Bien bao cho ngoat nguy hiem ben phai",
    37: "W.202a - Bien bao cho ngoat nguy hiem lien tiep, cho ngoat dau tien huong ben trai",
    38: "W.202b - Bien bao cho ngoat nguy hiem lien tiep, cho ngoat dau tien huong ben phai",
    39: "W.203b - Bien bao duong hep phia ben trai",
    40: "W.203c - Bien bao duong hep phia ben phai",
    41: "W.205a - Bien bao duong giao nhau kieu chu thap",
    42: "W.205b - Bien bao giao nhau co nhanh ben phai",
    43: "W.205d - Bien bao giao nhau dang chu T",
    44: "W.207a - Bien bao giao nhau voi duong khong uu tien",
    45: "W.207b - Bien bao giao nhau voi duong khong uu tien ben phai",
    46: "W.207c - Bien bao giao nhau voi duong khong uu tien ben trai",
    47: "W.208 - Bien bao giao nhau voi duong uu tien",
    48: "W.209 - Bien bao giao nhau co den tin hieu",
    49: "W.210 - Bien bao giao nhau voi duong sat",
    50: "W.219 - Bien bao doc xuong nguy hiem",
    51: "W.221b - Bien bao duong khong bang phang",
    52: "W.224 - Bien bao duong nguoi di bo cat ngang",
    53: "W.225 - Bien bao nguy hiem co tre em qua duong",
    54: "W.227 - Bien bao co cong truong thi cong",
    55: "W.233 - Bien bao nguy hiem khac",
    56: "W.235 - Bien bao duong doi",
    57: "W.245a - Bien bao di cham"
}

model.model.names.update(new_names_dict)