# Generated by Django 5.1.1 on 2024-09-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lane_detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laneimagemodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
